include:
  - immich/compose.yml
  - calibre-web/compose.yml

services:
    ts-immich:
      image: tailscale/tailscale
      container_name: ts-immich
      hostname: immich
      restart: always
      environment:
        TS_AUTH_KEY: ${TS_AUTH_KEY}
        TS_STATE_DIR: /var/lib/tailscale
        TS_EXTRA_ARGS: --advertise-tags=tag:container
      cap_add:
        - net_admin
        - sys_module
      volumes:
        - /dev/net/tun:/dev/net/tun
        - ./tailscale/immich:/var/lib/tailscale

    ts-calibre-web:
      image: tailscale/tailscale
      container_name: ts-calibre-web
      hostname: calibre
      restart: always
      environment:
        TS_AUTH_KEY: ${TS_AUTH_KEY}
        TS_STATE_DIR: /var/lib/tailscale
        TS_EXTRA_ARGS: --advertise-tags=tag:container
      cap_add:
        - net_admin
        - sys_module
      volumes:
        - /dev/net/tun:/dev/net/tun
        - ./tailscale/calibre-web:/var/lib/tailscale