services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: always
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - ./images:/app/public/images
    environment:
      PORT: 80
      HOMEPAGE_ALLOWED_HOSTS: home.chanelng.com
      HOMEPAGE_VAR_SHARED_CALENDAR: ${HOMEPAGE_VAR_SHARED_CALENDAR}
