---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/bookmarks

- Links:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Reddit:
        - abbr: RE
          href: https://reddit.com/
    - YouTube:
        - abbr: YT
          href: https://youtube.com/
