---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services

- My Apps:
    - Books:
        icon: calibre.png
        href: https://calibre.chanelng.com
        description: Calibre Web
        container: calibre-web
    - Photos:
        icon: immich.png
        href: https://immich.chanelng.com
        description: Immich
        container: immich_server
    - Syncthing:
        icon: syncthing.png
        href: http://chanel-server.tail14cd7.ts.net:8384
        description: Syncthing
        siteMonitor: http://chanel-server.tail14cd7.ts.net:8384
