name: Check for new Immich releases and update compose.yml if necessary

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # 8AM UTC daily

jobs:
  check-new-version:
    runs-on: ubuntu-latest
    env:
      IMMICH_COMPOSE_FILE: immich/compose.yml
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Pull latest compose.yml and overwrite existing
        run: |
          curl -L https://github.com/immich-app/immich/releases/latest/download/docker-compose.yml -o "$IMMICH_COMPOSE_FILE"

      - name: Create PR if there were changes
        uses: peter-evans/create-pull-request@v7
        with:
          title: Update immich compose.yml
          commit-message: "Automated: Update immich compose.yml"